### ISSUE TITLE
Guild Rank Specific EP

### ISSUE THREAD

**Issue by enevarez3** [Alumian/CEPGP-Retail#108]
This may be a question more than a feature request because I can't figure it out.  It would be nice if I could set CEPGP to only adjust the officer notes of my "Raider" Ranks.  I like to use the officer notes for my casual ranks for other things than tracking EP.  For example, when a person joins the Guild I like to include the date they joined for their ranks, so that I can promote them after their trial period concludes.  If they join to be a raider, then I am okay using their officer notes for EP.

**Comment by DeanAles** [comment]
Download Guild Roster Manager, much better than this option, because oficier note was always only for EPGP. I am using DGR and its awesome! :)

**Comment by Alumian** [comment]
Hi @enevarez3, I'm sorry for taking so long to get back to you on this. Unfortunately I don't believe that there is a "safe" way for me to implement this because some guilds may have multiple players that can edit officer notes and if they had conflicting settings then they would just go overwriting each other. Because of that, I'm afraid I won't be implementing this feature.
