### ISSUE TITLE
[Request] Possibility to make separate tables for different raids

### ISSUE THREAD

**Issue by Necrosium** [Alumian/CEPGP-Retail#122]
Could you please add a possibility to use separate EPGP tables and values for different raids. 

So our guild want to use MC values only for MC, Ony only for Ony, BWL only for BWL, etc

**Comment by Alumian** [comment]
Hi Necrosium,
Thanks for submitting this feature request. Unfortunately, since the EPGP values are stored in the officer note and has character restrictions, this is not possible to do outside of saved variables. The drawback of using saved variables to approach this is that they constantly need to be verified from player to player to ensure that the data is valid, but also it is highly susceptible to data loss, especially if the saved variables files need to be cleared due to UI errors. Because of those reasons, this feature will not be implemented.
