### ISSUE TITLE
[Request] Option to include Standby list with manual raid EP awards

### ISSUE THREAD

**Issue by Tragalix** [Alumian/CEPGP-Retail#130]
I would find it most helpful to be able to include those on the standby list when I manually award EP's to the raid, much like how they can be optionally included with automated awards from boss kills. At the moment I have to award the EP's twice, once to the raid and a second time to the standby list.

**Comment by Alumian** [comment]
Hey Tragalix, thanks for the feature request. At this stage I don't plan to implement this, just because it's 3 extra clicks for you and a lot more work for me. That, and a new option in awarding EP is a new way that EP can be accidentally mis-awarded. So at this stage I'm going to decline this and ask you to use the award standby EP button instead. Please don't let this shy you away from submitting feature requests in future.
