### ISSUE TITLE
[Question] Do you need my features? ^_^

### ISSUE THREAD

**Issue by SlavaSkvortsov** [Alumian/CEPGP-Retail#158]
Hi! First of all, thank you for the addon, you did a really great job!
Me and my guild just started to use EPGP system and I've done some features for the addon
1) Added 3rd type of points - Bank Points, we give them for an activity inside the guild and you can spend them buying items from guild bank
2) It was hard for me to retain to give EP every hour, so I did a system that tracks every person in raid and adds him a bit of virtual points, every hour I get a window where I can flush collected EP to the officer note
3) We decided to motivate raiders to use flasks and food by EP, so I check buffs before every pull and add points if there is any of them (by addon, ofc)

You can see the source here https://github.com/SlavaSkvortsov/CEPGP-Retail
If you think some of this features could be useful to others, I can do pull requests

**Comment by Alumian** [comment]
Hi Slava! Thanks for the work you've done. For the first point, I don't think that's something that I'm interested in adding in to the base addon, however I do recommend that you package that into a plugin - I'll be improving support for plugins in the coming versions. For the 2nd point, I feel like I will add in periodic EP gains since a lot of people have been asking for it and the 3rd point - I am currently working on a plugin from a request I received a long time ago for this addon which does just that. Please see #12.
