### ISSUE TITLE
[Request] Tier based pricing structure similar to ShootyEPGP

### ISSUE THREAD

**Issue by Anilusion** [Alumian/CEPGP-Retail#16]
https://github.com/Road-block/shootyepgp/wiki/Basics-Home

This wiki page explains it, and prices.lua is probably also of interest.

I would love if you addon would support a pricing structure like this old addon did. I think Item Level based GP prices are very bad fit for vanilla, as many lower level items are better than higher level items, and many items with the same item level are vastly different in actual power. 

ShootyEPGP also has a progression based pricing system that adjusts prices depending on what content you are doing. MC epics are expensive when you are progressing through MC and BWL, but very cheap if you are progressing through naxx.

I know this is a lot to ask, but ShootyEPGP really nails the pricing for vanilla itemization, and I would love to be able to use that system for our guild once we start raiding.

**Comment by Alumian** [comment]
Hi Anilusion, thanks for the request!
I've checked out Shooty EPGP and given some thought to your request, unfortunately at this time I am not planning on implementing this feature. The reason for that is, I understand and agree with your point about the same item level items having vastly different value to players, but unfortunately due to the way that I have elected to write the addon, it would take a significant change to adjust the calculation in the fashion that you're proposing. As an alternative, rather than inflating the GP of valuable items, I recommend adding less useful items to the addon override list so that you don't need to change the GP value every time you see an item.
In terms of the GP modulation, it's the same kind of deal. The easiest way that you can achieve this using the existing features is just change the GP multiplier. It's more manual than what I think you're searching for, but it really would take me an eternity (and potentially a lot of road bumps) to implement what you're asking.

So at this stage, I do apologise, but I won't be implementing this feature. Please don't let this discourage you from submitting feature requests in the future.

Regards,
Alumain
