### ISSUE TITLE
[Question] Decay, Rounding

### ISSUE THREAD

**Issue by Jh16** [Alumian/CEPGP-Retail#162]
**Please describe your question below**
So I'm curious on what the addon is set up to do for rounding.

Currently we are keeping a backup of the data through the use of google spreadsheets. And I've seen a slight problem.

Say a person has 12GP and you apply the decay of 10%. With decimals it's at 10.8, typically you should round up if the decimal is ".5" or higher and round down if lower than ".5". I have it in the spreadsheet as 11GP and the addon has it at 10GP (which is our base value).

As a math person this really kind of erks me and I'd prefer to not have to go through everyone's EP and GP just to correct a rounding problem. xD

**Comment by Alumian** [comment]
Hey Jh16, thanks for the question.

Are you on the CEPGP discord? I've just posted a question that I'd like to invite you to chime in on regarding this ticket. I'm a bit uneasy adjusting the arithmetic logic in the addon this far in at the risk of impacting the immediate "fairness" of guilds' implementations.

https://discordapp.com/channels/632720314236665859/632720314236665861/655155226034307078

**Comment by Alumian** [comment]
Hey Jh16,
Just to reiterate our discussion in discord - as it has been a design choice (pretty bad design choice at that), it makes it a challenge to rationalise implementing logic changes as so many guilds use the addon now. We decided that the overall benefit wouldn't trump the potential headache from forcing guilds to conform to this change.
The only solution I could offer to mitigating the impact it has when applying a decay is to inflate the numbers by a common factor so that decimal places have less impact.
