### ISSUE TITLE
[Request] Manually adding EP to standby list

### ISSUE THREAD

**Issue by Grimpeh** [Alumian/CEPGP-Retail#22]
I'd love to be able to add EP to standby list.
My guild operates with incentives like awarding EP for arriving on time and for being present during the end of the raid.

**Comment by skombag** [comment]
Yep my guild uses those awards too , and as it is now ppl on the standby list just get the credit from the bosskills not from manual raid awards.

**Comment by qrsu0203** [comment]
Was wondering if this would be added as well -- my guild awards EP based on time intervals and I noticed it's pretty difficult to grant EP to those on Standby. Any word on if this will be added in?

**Comment by Alumian** [comment]
Hey guys,
Sorry for the radio silence. Yes this sounds easy enough, I'm happy to add this in. I should be able to add it in in the near future - I've just dealt with a bunch of bugs and I'm still working out a few. I'm also in the middle of re-writing the guild/raid/standby scrollbars because to be honest, the way I wrote them initially is a complete joke. Also the loot council feature is low key busted at the moment so I'm working on fixing that too haha. I'll try my best to work this into the next update because this does sound like a very simple feature to put in, but can't make any promises this very second.
Thanks for your patience!
