### ISSUE TITLE
[Request]Can alt management be applied to non-guild/other-guild Member？

### ISSUE THREAD

**Issue by Se7enMuting** [Alumian/CEPGP-Retail#252]
Can alt management system be applied to the ALT member who is non-guild/other-guild member？
Want to achieve this function: first establish a scoring role(main) in the guild, and then synchronize the scores of non-guild/other-guild member(alt) to this role(main).

**Comment by Alumian** [comment]
Thanks for submitting your feature request. At this time I do not intend to implement this feature. The reason being, to store standings for players not in the guild, they would need to be stored in saved variables. Saved variables are too volatile to store that kind of information, especially because a common troubleshooting step for addon problems is to delete the WTF folder, which contains the saved variables. Additionally, it would require constant synchronisation between players which would cause additional network and client strain.
