### ISSUE TITLE
[Question] CEPGP:Error - You don't have access to modify EPGP

### ISSUE THREAD

**Issue by GatsbyHe** [Alumian/CEPGP-Retail#256]
Hi Sir or Madam,

I'm a vice President of the guild from China, but i can't award a member EP.

The Error is:You don't have access to modify EPGP

Could you please help me check it ?

Thank You.

Gatsby

**Comment by Alumian** [comment]
Hi Gatsby,
If you're getting that error, that means that your rank does not have access to modify officer notes. Talk to your guild leader and ask them to give that permission to your rank.

**Comment by murphy1312** [comment]
@Alumian 
sorry in advance for commenting on a closed issue, just to clarify:
if someone removes the CanEditOfficerNote() lines he can edit everything? 
shouldnt there be some kind of security?

**Comment by Alumian** [comment]
No problem :)
It's not an issue because even if someone were to remove that check, the permission is delegated server-side by the guild master, not by the add-on. This check is merely in place to ensure that unexpected results don't happen.
Essentially, CEPGP piggybacks off the in-game guild permissions.
