### ISSUE TITLE
[Bug] GP decay amount incorrect

### ISSUE THREAD

**Issue by Ohnoto** [Alumian/CEPGP-Retail#259]
Our guild runs a weekly decay amount of 15%. 

This week mine was at 83 before the decay. 
After the decay it went to 73. 

15% rounded should have put it at 71. 

The EP amount was decayed correctly.

**Comment by Alumian** [comment]
Please attach your /cep debug dump to this ticket.

**Comment by opala-wow** [comment]
Our guild is also showing the same issue.  Seems this may have been going on for some time as the PR ratings are now skewed (PlayerA was higher PR than PersonB and is now lower than PersonB after decay).  

I've attached our debug report and I am the one who issues decay.
[CEPGP debug 5.14.txt](https://github.com/Alumian/CEPGP-Retail/files/4626035/CEPGP.debug.5.14.txt)

**Comment by Ohnoto** [comment]
Here is my debug dump.
[CEPGP Debug 051420.txt](https://github.com/Alumian/CEPGP-Retail/files/4626095/CEPGP.Debug.051420.txt)

**Comment by Alumian** [comment]
Thanks guys. For future reference, the debug is formatted for use with GitHub, so there's no need to upload it into a file. I have edited your posts for you.

@Ohnoto: You have enabled the decay-free threshold. The behaviour of this function is that it changes the decay so that instead of decaying with 83 as the base, it decays with 63 as the base (because you have the minimum GP set to 20). So the calculation changes from 83 x 0.85 to 63 x 0.85 and since CEPGP always rounds down, 83 - (63 x 0.15) = 73.55 = 73.

@opala-wow: Are you the person issuing the decay?
