### ISSUE TITLE
[Bug] Traffic Sync Preventing New Entries

### ISSUE THREAD

**Issue by Jh16** [Alumian/CEPGP-Retail#287]
**The Error**
What was the error message you received?
*No error message*

**Describe the bug**
*When the traffic is shared, during the sharing process if new entries are done. Those who are on the receiving end of the share won't get their traffic log updated with new traffic data.*

**To Reproduce**
How can this bug be reproduced?
*Have someone share traffic data with 900+ entries, kill a boss, do loot, check traffic log of receiving end of the share.*

**Debug Information**
Type /cepgp debug and copy and paste the information into this bug report.

**Comment by Alumian** [comment]
Hey Jh16,
This is actually a design choice. Since sharing existing entries and creating new ones run through the same process, the process essentially locks during the sharing process to ensure that that traffic on either side is not modified during the import process. I recommend just being cautious about when you choose to share logs.
If this starts to become a real problem then I may look at changing this.

**Comment by Alumian** [comment]
Jh16 has explained the issue presented by traffic sharing locking establishing new entries for the period.
This will be investigated.

**Comment by Alumian** [comment]
Resolved in 1.13.0.
