### ISSUE TITLE
[Request] Note / Reason freetext field for EPGP Traffic frame

### ISSUE THREAD

**Issue by PibbzTV** [Alumian/CEPGP-Retail#3]
**Describe the feature you'd like to see in this addon**

First of all, great addon!
Now, I have tested it a bit on the beta, and I foresee that X amount of drama could be avoided by having a field for Note / Reason as to why EP was adjusted individually. Like you give Manbear the Druid +10 EP for donating Potions to the guild, but nowhere to document the reason those +10 EP was added.  

Other players might wonder why Manbear recieved +10 EP down the line, and if  you dont remember, you're screwed. This would be a very valuable addition :)

**Comment by Alumian** [comment]
Hey Pibbz,
Thanks for the suggestion! I'm actually surprised no one has requested it in the past lol. It doesn't sound difficult to implement, I'll have a crack at it and keep you posted.

**Comment by Alumian** [comment]
Hey Pibbz,
I've given this some thought and yeah I really don't think this would be especially difficult to implement. Unfortunately, I won't be able to implement this feature until the Classic launch. Reason being, I unfortunately don't have access to the beta and the stress test was really my only opportunity to do bug/feature testing. Since the current retail API is not 100% compatible with the new Classic API, I can't test it on retail. But I'm happy to implement this feature for you.

**Comment by PibbzTV** [comment]
That's great! No rush, we won't be raiding until late september at the earliest anyway :) Thanks <3

**Comment by Alumian** [comment]
Hi Pibbz,

Just letting you know that your feature request has been pushed out in version 1.11.0 just now.

Thanks,
Alumian

**Comment by PibbzTV** [comment]
Cool AF man! Thanks alot :) We'll keep in touch <3
