### ISSUE TITLE
[Question] Lootmaster addon required?

### ISSUE THREAD

**Issue by PibbzTV** [Alumian/CEPGP-Retail#4]
**Please describe your question below**
Hello. It's me again. Sorry for bothering you on a daily basis lately, but I'm preparing for Classic and want as much administration as possible sorted out during the beta :)

I got everything set up the way I wanted, but Im not able to test how it works when actual loot is involved. Does it automatically trigger a "Mainspec/Offspec/Pass" type popup for raidmembers that also got the addon installed? Do I as a masterlooter get a Masterlooting frame which displays who needs what?

Im visualizing something along the lines of this addon: https://www.curseforge.com/wow/addons/epgp_lootmaster/screenshots - do we need something like this in addition to CEPGP? Or will this one do it all? :)

**Comment by Alumian** [comment]
Hey PIbbz,

Don't worry you can ask for features or ask questions as much as you like haha. Essentially, this is a standalone addon. The way it works is, when you're in a raid and you are the loot master, the frame will automatically appear when you see an item of a certain quality drop. Alternatively, you can manually open the frame at any time while looting to distribute any item (except white/gray items as they can't be distributed via master loot). When the frame appears, you will see an entry for each item along with a red 'Announce' button to the left of it. You click the button and it sends a raid warning out with the details of the item and to whisper you !need if they want the item. At this stage, the addon doesn't support greed/offspec, but that may be something that we can look into in the future (I'll need you to submit a fresh ticket for that feature request if you want that).
Also just as a side note, the "loot council" support that I keep jumping up and down about is, your raid assists can see everything that you can see when people message you. That way, if you want to have LC discussions, you're all on the same page with what you're seeing.
Anyway, once a player has messaged you with !need, it'll compile their information into a table for you and you can choose from that table, who to give the item to. Essentially, the information displayed is similar to what you can see in https://media.forgecdn.net/attachments/91/313/ML_bidding.jpg except my addon doesn't show their response (since there is only one response at the moment), their roll, bid, votes and ilvl.

Sorry for the essay, but does that answer your question?

**Comment by PibbzTV** [comment]
Seems good! After talking with the officers about this approach, they were curious if it was possible to have some sort of public bids instead of in a whisper? Just to make everything more transparent and have less conspiracy theories pop up :)

**Comment by Alumian** [comment]
Sure, so just first thing I need to clarify is that EPGP isn't a bidding system. It works in a ranked priority fashion where EP divided by GP = priority (PR). Because of this, a players rank only changes if someone has a higher priority than them.

Having said that, when a player responds !need on my add-on, the loot master involuntarily reports in raid chat just that. It reports to the entire raid the name of the player, their class and their priority. Once the loot master starts accepting responses for an item, they are unable to modify the GP of an item.

Is that what you were asking?

**Comment by PibbzTV** [comment]
Allright, perfect! Yes I know it's not a bidding system, but i still want everyone to know who's interested in an item when it drops. Full transparency during loot distribution is always a good thing :)

**Comment by Alumian** [comment]
No worries, so I just had to check my code because I'm not at home at the moment to test lol, when a player responds with !need, the loot master will print out the following as an example:

> Alumian (Mage) needs. (5,000,000 PR)

If the player isn't a guild member, then it prints out in the following fashion:

> Alumian (Mage) needs. (Non-guild member)

This change is in case you pug someone - it is assumed that the pug won't have any EPGP.

**Comment by PibbzTV** [comment]
Perfect! Thanks again, Sir :)

**Comment by PibbzTV** [comment]
Oh and by the way, IF you choose to implement the greed/offspec feature, make sure it's up to the master looter to have it enabled or not. This addon seems to be perfect for what we want to do with free rolls for offspec. More buttons available to the raiders would only end up confusing them :)

**Comment by Alumian** [comment]
Sounds good. Also, the next stress test seems to be public so fingers crossed I'll be able to work on some of these features again ^^

**Comment by PibbzTV** [comment]
Just to make sure I have understood the GP forumla correctly, could you provide me with the GP cost of Bonereaver's Edge using default values for slotweights for me to compare?

**Comment by Alumian** [comment]
Okay so to calculate GP, the following formula is used:
`math.floor((COEF * (2^((ilvl/26) + (rarity-4))) * slot)*MOD)*quantity`

To elaborate a little bit, math.floor simply takes the value and if it isn't a whole number, it rounds it down (thinking of revising this part). COEF is the base coefficient. I've been told recently that the coefficient that I've been using is actually the one for WOTLK (which is why the GP for everything is really low, also thinking of raising the base coefficient to be more sensible), but hey that's why I put in the option to change it lol, so that you can adapt it to your guild's needs. ilvl, duh, slot, duh lol, MOD is simply just a static modifier if you feel like inflating your GP and quantity is the number of the item that drops (only applicable to items that stack). Oh and rarity is just the numerical representation of the item's rarity. 2 is uncommon, 3 is rare, 4 is epic, and so on.

To answer your question:
`GP = math.floor((0.483 * (2^((77/26) + (4-4))) * 2) * 1) * 1`
`((0.483 * (2^((77/26) + (4-4))) * 2) * 1) * 1`
`GP = ~7.52`
But since we've got math.floor in there, GP = 7.

That is, assuming my maths checks out. It's 7:30am, what do you want from me. I just live here okay *throws papers everywhere*

**Comment by PibbzTV** [comment]
Hahahah :D Telltale sign of you going mad! 

Thanks a lot! The (*quantity) seems to be a variable i can define in the addon. Is this intended for boosting the GP cost of an item? Say we use default EP values * 10. Could we use the (*quantity) to do GP * 10 aswell? 

Hope you understand what I mean, its almost midnight here in Norway :D

**Comment by Alumian** [comment]
Go to bed already lol
Yes absolutely, I mean you might trip over if you want you want to distribute an item that is in multiple stacks (for example, if you wanted to distribute essence of fire for some reason, it can drop in stacks of more than 1, thus the GP value for that single distribution would be multiplied by quantity).
The variable that was designed for this though was MOD. That variable multiplies the final GP value of one unit of an item. Now that I think about it....it doesn't actually make a difference which of the two you modify haha.
Regardless, you certainly should be able to modify **almost** any part of the GP formula. See my attached screenshot. Is it not displaying/behaving like that? This screenshot was taken on a 1.12.1 (
![CEPGP_Options](https://user-images.githubusercontent.com/24452898/60746369-c4c10780-9fc1-11e9-8ea3-0a861d903884.PNG)
 client.

**Comment by PibbzTV** [comment]
What a flippin' gent you are mate. Thanks a lot once again! This will be perfect.

The only reason I want to adjust the base EP and use a higher GP is because rounding errors become less significant with higher numbers. Once you apply decay and the resulting EP or GP would be a decimal number, the rounding of these values up or down can cause the PR value to change too much in either direction with low values :)

Addon looks just like yours btw.
![Capture](https://user-images.githubusercontent.com/51060651/60746837-873c8a00-9f81-11e9-960e-fb952e97fda0.JPG)

**Comment by Alumian** [comment]
Haha no worries. Yeah so I mean really either just change the first or last value and it will scale linearly. You can always give it a try on *any* drop of you type /CEPGP debugmode (enjoy the spam in chat) and open the loot window. Just a word of warning, that's my debugging mode as the name suggests, so you will get access to menus and functions which would usually have prerequisites, so stuff may break (nothing a UI reload won't fix) if you turn it on.
