### ISSUE TITLE
version command doesn't work[Bug]

### ISSUE THREAD

**Issue by swarlington** [Alumian/CEPGP-Retail#48]
after loading the newest update /cepgp version doesn't work out of the gate anymore, for me it worked once i did /cepgp and /cepgp show, but some guildies say even that doesnt do it for them

**Comment by Alumian** [comment]
Hi Swarlington,
I've just tried that on my own client and yep I'm hitting the same issue. It looks like the guild roster isn't caching fast enough, which was actually I measure I introduced in this version to counteract a huge lag issue that was caused by the addon.
I'll start working on a solution but for the time being, I recommend just giving it a bit of time before trying to access the version frame so that it can poll the guild information.

**Comment by Alumian** [comment]
Should be fixed in the latest hotfix. Can you please confirm if you are still having this issue?

**Comment by swarlington** [comment]
yes its indeed fixed, thank you!
