### ISSUE TITLE
[Question] Do you have a discord for this Add-on?

### ISSUE THREAD

**Issue by sostoked** [Alumian/CEPGP-Retail#59]
**Please describe your question below**
It would be really useful for noobs like myself to have a discord for this addon to trade ideas on GP formula and item values etc. Any chance you could link to a channel?

**Comment by Alumian** [comment]
Hey sostoked,
I don't have a CEPGP discord at this stage, but I'm happy to start one for discussion purposes only. I'll just pilot it for the time being and see how it goes, kinda stretched thin for time since I'm juggling my job, guild leading, raid leading, my personal life and this addon lmao.

Check out the discord here: https://discord.gg/7mG4GAr
