### ISSUE TITLE
[Bug] The Bug trio +10 EP given out randomly

### ISSUE THREAD

**Issue by VidyaViking** [Alumian/CEPGP-Retail#64]
Not sure if this is a bug or something we've fucked up in the settings but now and again the addon just gives out +10EP to everybody in the raid and it's always for "The Bug Trio". It doesn't matter who's the raid leader/LM either.

**Comment by Alumian** [comment]
As in like.....even when things aren't being killed?

**Comment by VidyaViking** [comment]
> As in like.....even when things aren't being killed?

It did it mid Onyxia fight once.

**Comment by Alumian** [comment]
Okay...because the pathway for this to happen is something dies, my addon matches the thing's name against my database of names and if it matches (and auto award EP is turned on) then it awards the respective amount of EP. So you say it happened regardless of who was the Loot Master? Can you add me to discord so that we can discuss further? Alumian#6465

**Comment by Alumian** [comment]
I've spoken with Vidya and it turns out that they have someone in their guild named Vem. When Vem dies, it causes a misreading by CEPGP thinking that a member of the bug trio has been defeated.

**Comment by Lanly-Lanly** [comment]
That is a very good news! Does customized item GP work by item names or IDs? I haven't tried that yet, but it would be awesome if that is applicable to non-English client as well. Many thanks!

**Comment by Alumian** [comment]
Nah so items in the override list shouldn't have this problem. As long as you're adding them to the list in the same language as your client (e.g. Russian client means you need to put the item name in Russian). Essentially, the add-on just looks at the loot table and checks to see if it recognises any names there from the override list.

**Comment by leinstay** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/8215580/67008564-6e9c4e00-f0f2-11e9-90cb-1ab386a66cff.png)

@Alumian  I don't know if this is related to this bug or I should create new ticket, please advice me. 

Yestarday I found out that after we gave EP for boss kill, our random guild members received EP too (1-40 guys that doesn't even raid with us) and even more importantly, some EPs have been reduced randomly, and in some cases GP was reverted to 1. 

We collect the entire history of the guild's notes, so we can keep track of such things. Examples:

Guild member 1 was not in raid and his note changed from 0,1 to 8061,1, he now have more EP than anyone
Guild member 2 was in raid and his note changed from 7711,1 to 8011,1, this is okay
Guild member 3 was in raid and his note changed from 3000,43 to 1850,1

**Comment by Alumian** [comment]
Hey guys, I'm sorry this has taken so long to hit up. I've found a fix that is far far far simpler than converting the whole table to IDs, it did however require that I implemented localisation. But that's fine, it's done now. We shouldn't see this issue again. The fix is now available in beta 3 on the CEPGP discord. Please let me know if you see this issue again.

**Comment by Alumian** [comment]
Fixed in https://github.com/Alumian/CEPGP-Retail/releases/tag/1.12.7
