### ISSUE TITLE
[Feature] Decimal Places for Player EPGP

### ISSUE THREAD

**Issue by hbjose** [Alumian/CEPGP-Retail#72]
It is possible to implement a support for more decimal places?
It doesnt make a difference if an item´s value is 2,1 or 2,9.
I cant add GP with decimal places.

**Comment by Alumian** [comment]
This isn't a bug, I just haven't fully implemented the feature just yet. I've come across some issues which I'm thinking very carefully about how to address so that it doesn't cause guilds to explode as soon as the update rolls out.

**Comment by Alumian** [comment]
@Andrioden Decimal places is made necessary by the scale of the GP values that the guild decides to use. They could definitely use a x10 value system and yes that would solve the problem, but if it's not something they _want_ to use, then I'm not going to force it on them. But at the same time, that's what's making this feature so incredibly difficult to work out.

**Comment by Andrioden** [comment]
So the danger is in the use case:
1. Officer 1 saves data in decimal places 2.9
2. Officer 2 saves data in integers, the addon rounds it to 3 (or 3.0)
3. Now 0.1 is lost.

I would say, without knowing everything about the addon, if you want to support this; completely convert the addon, and every part of it its number storage, including number storing to decimals places, decide allready now what decimal precision you want, and reuse that precision everywhere with a common method to ensure consistency "DevideByEnsureDecimals()" and "RoundToDecimals()". The only downside to this is that guilds like mine will now always see 100.0, 230.0, etc numbers, which is annoying. So then maybe, ontop of this add a configuration where addon users may say "ShowNumbersRoundedWithoutDecimals", not changing the way its stored, but only how it is presented.

When that is said, my overall feedback is to not implement it since it gives no new functionally and only potential problems. If you think about it on a high level, 101 and 10.1 contain the same amount of precision as long as all parts of the number handling is consistently handling it, because at some point you have to round it to either number either round 101.9 up to 102, or 10.19 up to 10.2.

__A bit off topic__
It is an interesting topic, which I did a bit research on when deciding what format i wanted to store currency (which is very sensitive) in, it is not uncommon to store currency in whole/integer numbers and convert it to decimal places when presenting it. Ironically enough I went with a two decimal storage format (100.11) for all currency, but that was to avoid any programming confusion since thats how we think about our currency in Norway, but I had the advantage of a good database and building the system completely from scratch, I would never change it now. : P

**Comment by Andrioden** [comment]
Also, while at the subject, I would like if the ratios have consisent amount of numbers in the guild overview, raid overview and masterloot window, so:

0.21
0.2
0.19

is shown as

0.21
0.20
0.19

**Comment by Alumian** [comment]
An interesting perspective. I'm not really going to focus on this feature for a whole tbh but I will say that it's important to know that the add-on rounds down by default, not to the nearest whole number. Meaning the difference between 2.9 and 3.0 isn't 0.1, it's actually 1.0.

**Comment by Alumian** [comment]
Alright, after extensive consideration and discussion, I have decided not to support decimal places. I understand that it is extremely inconvenient, but it simply poses far too much risk. The only solution I can offer is to upscale your EPGP standings to accommodate for the lack of decimal places. My apologies that it has taken this long to come to a decision, but this was a far larger issue than most people realise and it has significant implications.
