### ISSUE TITLE
[Request] Raid Attendance sorting

### ISSUE THREAD

**Issue by MrFergus** [Alumian/CEPGP-Retail#74]
When you're snapshotting the raid attendance, could you do it so you have different sections for the people inside the raid, the benched people and then overall

**Comment by Alumian** [comment]
In the current version, both the benched players and the players in the raid are shown on the same window but in two different scroll frames. Does that satisfy your feature request? Because tbh to add an overall it'd probably be a lot more effort than it's worth since you can really see everything on one window.

**Comment by Alumian** [comment]
Implemented a while ago in a previous version.
