### ISSUE TITLE
CEPGP - Retail Formula 

### ISSUE THREAD

**Issue by stefoxy** [Alumian/CEPGP-Retail#76]
Regarding ticket with wrong formula in Repository CEPGP
Part of the formulas are 0.483 and the addon we have is 4.83 is this right value please give me example of normal default settings that we need to use.

Just to get it right
Are the Boss EP stays 5EP per MC boss or we need to boost it for 10EP per boss or more?
I don't want to break the formula with changing the other things.
Thank you for the fast response.
Please advise.

**Comment by stefoxy** [comment]
"previous Question
4,83 x (1^ ((ilvl/26)+(rarity-4)) x slot) x 1 
Will bring same results no mater what item level and rarity is the loot only the slot itself because 1^any number is 1. Which is pointless to have rarity and ilvl in their at all if this is the case. Please follow up on this because most of the formulas are having 2 instead of 1 that we get on default when installing the addon. 
Let me know if we are wrong or the addon got a bug with the latest updates and formula is not correct. Using 1.12.4 "

**Comment by mykkenny** [comment]
Was wondering this same thing after typing out the formula in another ticket. Possibly just a typo on the UI?

**Comment by skombag** [comment]
there is a reason the formula is editable use it as you please.

**Comment by Alumian** [comment]
The default formula was changed several versions ago but it will not update because your game already has a set of saved variables for the formula. You need to change the formula yourself. The original formula was 0.483 X (2^... But I was informed that that is the WOTLK formula, so to accommodate for classic item levels, I inflated it from 0.483 to 4.83. there are no correct or incorrect values, you need to experiment and find out what works for you and your guild.

**Comment by Alumian** [comment]
Also the boss EPs are what ever is set on the 3rd page of the options menu.
