### ISSUE TITLE
[Request] Off spec options and more

### ISSUE THREAD

**Issue by daiqll** [Alumian/CEPGP-Retail#82]
Hi,
Thank you for your great work to keep epgp alive on classic server. English is not my first language, so sorry if anything is confusing. 

Right now when using the UI option, raiders with the addon can see a window like this.
![image](https://user-images.githubusercontent.com/56465944/67302427-de2d8700-f4be-11e9-8983-a9f6a6bb9b64.png)

There need to be more buttons than Main spec and pass. *
The button should be customizable by Master looter in setting and each option should be assigned with different % of GP. (like 100% for the main spec, 50% for off-spec and such). *

Following is an example for the option taken from RCLootCouncil we are currently using together with CEPGP. Where I can choose how many buttons to have, and under Button 1,2,3, I can type in the text to display for each button, under response I can type in the percentage of full GP associated with that option. 
![image](https://user-images.githubusercontent.com/56465944/67302756-5d22bf80-f4bf-11e9-9a10-1ddd8cd0f29f.png)

As for the master looters UI table, I would suggest the following (in order of importancy):
1. Option to disable the raid announcement for people that rolled need. The raid announcement defeats the purpose of not showing the table to raid.*
2. Table sorted by raiders' picks suggested above (ex. Mainspec, Offspec) and by PR.
3. Option to keep this list visible only to selected people (master looter only / certain people by name / certain guild rank). right now it is either only me or the whole raid.
4. Options to change raiders' choice in case they changed their minds.

For standby list,
1. I know you mentioned on discord that the standby list is not a saved variable and will be lost when reload. If you ever come up with a way to make it persist after reloads, it would be also super helpful.
2. an option to automatically remove people who joined my raid from the standby list.

Lastly, a command to add an item manually for distribution for testing or other random purposes would be nice.

*I feel like those are the main priorities. 

Thank you again for your hard work!

**Comment by Alumian** [comment]
Hey Daiqll,

Thanks for the fantastic effort you've put into this feature request, but there is already a feature request open for this (please see #23). Just a few other things - In the latest beta version I pushed on Discord, I've made the standby list a saved variable so that will now persist between sessions and yes players will be automatically purged as they join the raid. I'll go ahead and add in the option to suppress the response announcements as per your first point, table sorting should already be in there though, just click the headers (pretty sure that's working). For your 3rd point, I'm still trying to work through that, I'm getting kind of mixed signals from people so I need to get to the bottom of it to see if there is actually a bug there or not. For your 4th request, tbh I'm probably not going to add the ability to remove people from the list, just because there are too many areas where that can cause problems within the addon and it's just easier to ignore that entry.

As the main feature already has an open ticket, I'm going to close this one as a duplicate. Thanks again for the effort you've put in to this request and it will be added, just keep an eye on #23.

**Comment by Alumian** [comment]
Just added the option to suppress loot response announcements, it's in the next version :)
