### ISSUE TITLE
Report list of core and standby players when mass EP is given. [Request]

### ISSUE THREAD

**Issue by afonsohfontes** [Alumian/CEPGP-Retail#84]
It would be great to have a list of names reported in the guild chat of those that were credited mass EP in events such as boss kills. Differentiating (in this report) those in the raid from those in the standby list.

This allows standby players to check if they are receiving the points they are supposed to receive correctly just by checking if their names are on the list.

I realize it is going to be a long list and some users might not like it. Maybe an option to show only those in standby and/or to toggle these reports would be great.

**Comment by Alumian** [comment]
This would result in unwanted spam in guild chat. As it stands, players on the standby list should be receiving a message via the addon to tell them that they have been awarded standby EP. Otherwise, the standby EP is recorded in the traffic log. At this stage, I do not intend to implement this feature.
