### ISSUE TITLE
Automate attendance Snapshots.[Request]

### ISSUE THREAD

**Issue by afonsohfontes** [Alumian/CEPGP-Retail#86]
It would be great to have an automated snapshot taken and saved to the attendance check every time a mass EP award is given.

The automated snapshot also needs to be shared with everyone (or triggered/recorded by everyone) so if the master looters miss one raid the real attendance would be saved in the addon of those who didn't.

**Comment by will5757** [comment]
People in the standby list now count for attendance snapshots, i requested this earlier and it was added

**Comment by afonsohfontes** [comment]
Great, @will5757 ! Thanks for the update.

**Comment by Alumian** [comment]
Unfortunately there is risk of it taking up too much space in the saved variables file with this feature. The file does have a maximum file size and it is very large, but I have had other addons hit that limit before and I want to avoid that with CEPGP. Efficient storage was one of my biggest concerns when adding attendance snapshots in the first place so at this stage, Also having an additional snapshot taken every time a mass award was given means that in theory, one run of Molten Core, which has 10 encounters, assuming you had a full raid of 40 players means you'd be adding at least 400 lines to the file for one full clear. Also sharing snapshots poses much the same problem.
Since all of this can be achieved with manual snapshots and if you really insist, file sharing, at this stage, I do not intend to implement this feature.

**Comment by afonsohfontes** [comment]
Hi alumian, where are the snapshots saved? Let me think of a way to make it viable. Maybe normilizing this data so you don't store infinite entries.

**Comment by Alumian** [comment]
Saved variables. It's the only place any data can be written.
