### ISSUE TITLE
[Bug] EPGP Decay Bugs

### ISSUE THREAD

**Issue by SaltMcSnark** [Alumian/CEPGP-Retail#98]
### 1. EPGP decay is rounded and can scramble priority order

https://github.com/Alumian/CEPGP-Retail/blob/master/Core.lua#L819-L820

These lines will round down decayed GP to the next integer, this causing large fluctuations in decay amounts for people near 0 GP (e.g. w/ a 10% decay, a player at 100/2 will decay to 90/1, changing priority from 50->90). Because the overall decay can be different from 1 and varies from player to player, decay events can wildly impact relative priority. Please consider rounding to the specified decimal precision in the options.

### 2. EPGP decay doesn't take into account minimum GP

The minimum GP is counted in the decay amount, which heavily advantages people with no gear. I believe the intended calculation is to decay only on the amount between the *difference between* your current GP and the minimum GP:

`GP = BASEGP + (tonumber(GP)-BASEGP)*(1-(amount/100));`

Otherwise, with a minimum GP of 20, someone with 22 GP will decay to the base GP of 20 with one decay cycle.

**Comment by Alumian** [comment]
Hey Salt,

Thank you for submitting this bug report. I have implemented a fix for decay not taking into account minimum GP in the next version. Unfortunately however, after extensive discussion and consideration, I have decided not to support decimal places in CEPGP. I understand that it should have been in there since the beginning, but implementing it at this stage poses far too much risk. I invite you to consider ticket #22 which contains many of the points that were being considered.
